import ui.*;
import ui.objects.SuffButton;
import ui.plugins.*;
import backend.Achievements;
import backend.Controls;
import backend.Constants;
import backend.Language;
import backend.Paths;
import backend.Preferences;
import backend.Utilities;
import backend.ScreenSafeArea;
import backend.WindowTitleUtil as Window;
// Flixel
import flixel.sound.FlxSound;
import flixel.FlxG;
import flixel.FlxBasic;
import flixel.FlxObject;
import flixel.FlxSprite;
import flixel.FlxCamera;
import flixel.addons.display.FlxBackdrop;
import flixel.addons.transition.FlxTransitionableState;
import flixel.animation.FlxAnimationController;
import flixel.group.FlxSpriteGroup;
import flixel.group.FlxGroup.FlxTypedGroup;
import flixel.group.FlxContainer.FlxTypedContainer;
import flixel.input.keyboard.FlxKey;
import flixel.math.FlxMath;
import flixel.math.FlxPoint;
import flixel.math.FlxRect;
import flixel.text.FlxText;
import flixel.tweens.FlxEase;
import flixel.tweens.FlxTween;
import flixel.util.FlxColor;
import flixel.util.FlxTimer;
import flixel.util.FlxSave;
import flixel.util.FlxStringUtil;
import openfl.utils.AssetType;
#if sys
import sys.*;
import sys.io.*;
#end

using StringTools;
